### ISSUE TITLE
Adjust curl options to use best practices

### ISSUE THREAD

**Issue by edmorley** [jakeg/heroku-buildpack-bun#14]
Currently curl is called with `-S` (this is different from the lowercase `-s`) which hides error messages:
https://github.com/jakeg/heroku-buildpack-bun/blob/cded310383f8809383e2608eafc08e1773cad266/bin/compile#L54

Also, it doesn't use timeouts or retries.

I'd recommend using some of the options we use in Heroku's official buildpacks, eg:
https://github.com/heroku/heroku-buildpack-python/blob/99684a6ffdb23e50a9a2ee0b59ddf3c5e865ea5d/bin/steps/python#L115

**Comment by jakeg** [comment]
I don't see a problem with `-sS` - the small `s` makes it silent in terms of showing status bars etc, then the large `S` overrides that silence in order to show errors. Surely that's desired?

I have, however, added retries in https://github.com/jakeg/heroku-buildpack-bun/commit/42225de7f368a0b99a7030c8b9f4a5827fb5e078 in case of eg temporary network issues.

**Comment by edmorley** [comment]
> then the large `S` overrides that silence in order to show errors.

Ah sorry you are right, I had that one inverted in my head for some reason!

Thank you for adding the retries :-)

**Comment by jakeg** [comment]
@edmorley I've added this buildpack to Heroku Elements many months ago, but it never appears when searching the web interface, eg at https://elements.heroku.com/search/buildpacks?q=jakeg or https://elements.heroku.com/search/buildpacks?q=bun . Can you possibly look into this? I'm concerned people may try to find a Bun buildpack and as there's not one listed there assume it's not possible to use Bun with Heroku, while clearly it is.
